[general]
import = [
    "~/.config/alacritty/aura_theme.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding = { x = 5, y = 5 }
dynamic_padding = true
opacity = 0.4
blur = false

[font]
normal = { family = "Cascadia Code" }
